# Generated by Django 4.2.2 on 2023-07-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_plantas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='macetas',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tierras',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
